export const BATCH_SIZE = 30;
export const MAX_CATALOGUE_LENGTH = 150;
export const ORGANIZATION = "reactjs";

export const GET_ORG = "GET_ORG";
export const GET_ORG_SUCCESS = "GET_ORG_SUCCESS";
export const GET_ORG_FAILURE = "GET_ORG_FAILURE";

export const GET_REPOS = "GET_REPOS";
export const GET_REPOS_SUCCESS = "GET_REPOS_SUCCESS";
export const GET_REPOS_FAILURE = "GET_REPOS_FAILURE";
export const GET_NEXT_REPOS_BATCH = "GET_NEXT_REPOS_BATCH";
export const GET_NEXT_REPOS_BATCH_SUCCESS = "GET_NEXT_REPOS_BATCH_SUCCESS";
export const GET_NEXT_REPOS_BATCH_FAILURE = "GET_NEXT_REPOS_BATCH_FAILURE";
export const ADD_NEXT_REPOS_BATCH = "ADD_NEXT_REPOS_BATCH";

export const GET_SPECIFIC_REPO = "GET_SPECIFIC_REPO";
export const GET_SPECIFIC_REPO_SUCCESS = "GET_SPECIFIC_REPO_SUCCESS";
export const GET_SPECIFIC_REPO_FAILURE = "GET_SPECIFIC_REPO_FAILURE";

export const SEARCH_REPO = "SEARCH_REPO";
export const SEARCH_REPO_SUCCESS = "SEARCH_REPO_SUCCESS";
export const SEARCH_REPO_FAILURE = "SEARCH_REPO_FAILURE";
export const CLEAR_SEARCH_REPO = "CLEAR_SEARCH_REPO";
export const CLEAR_SEARCH_REPO_SUCCESS = "CLEAR_SEARCH_REPO_SUCCESS";
export const CLEAR_SEARCH_REPO_FAILURE = "CLEAR_SEARCH_REPO_FAILURE";
